// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTUvvVdTvYcW-3MTeqtbtX6-NoHNngkjc',
    appId: '1:463959979616:web:6cb4d383e38528cdf17505',
    messagingSenderId: '463959979616',
    projectId: 'ecommerce-bb968',
    authDomain: 'ecommerce-bb968.firebaseapp.com',
    storageBucket: 'ecommerce-bb968.appspot.com',
    measurementId: 'G-JQR0BMXMM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDnA5N4--Y2njQPPkIM-DZpVkohpNLMx8',
    appId: '1:463959979616:android:c9d41ec6b0135279f17505',
    messagingSenderId: '463959979616',
    projectId: 'ecommerce-bb968',
    storageBucket: 'ecommerce-bb968.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9uQotY8h9YPD66vR9n_gMDpvC5589k3s',
    appId: '1:463959979616:ios:740fefd9d62c0c67f17505',
    messagingSenderId: '463959979616',
    projectId: 'ecommerce-bb968',
    storageBucket: 'ecommerce-bb968.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9uQotY8h9YPD66vR9n_gMDpvC5589k3s',
    appId: '1:463959979616:ios:740fefd9d62c0c67f17505',
    messagingSenderId: '463959979616',
    projectId: 'ecommerce-bb968',
    storageBucket: 'ecommerce-bb968.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTUvvVdTvYcW-3MTeqtbtX6-NoHNngkjc',
    appId: '1:463959979616:web:855dee48c3f04250f17505',
    messagingSenderId: '463959979616',
    projectId: 'ecommerce-bb968',
    authDomain: 'ecommerce-bb968.firebaseapp.com',
    storageBucket: 'ecommerce-bb968.appspot.com',
    measurementId: 'G-W8F95H240M',
  );
}
